export const data = [
    {
        id: "1",
        date: "5/20/2023",
        invoiceNo: "1LC3XQ",
        payer: "Green Kaya Limited",
        payee: "Bread Cheap Limited",
        amount: 485000,
        status: 2,
    },
    {
        id: "2",
        date: "5/19/2023",
        invoiceNo: "1LC3XQ",
        payer: "Green Kaya Limited",
        payee: "Tiositiz Public Joint",
        amount: 287000,
        status: 3,
    },
    {
        id: "3",
        date: "5/17/2023",
        invoiceNo: "1LC3XQ",
        payer: "Sun Pharma Limited",
        payee: "Bread Cheap Limited",
        amount: 935000,
        status: 1,
    },
    {
        id: "4",
        date: "5/10/2023",
        invoiceNo: "1LC3XQ",
        payer: "Marron Limited",
        payee: "Brew Estate Limited",
        amount: 257800,
        status: 2,
    },
    {
        id: "5",
        date: "5/20/2023",
        invoiceNo: "1LC3XQ",
        payer: "Great Beer Limited",
        payee: "MOB Limited",
        amount: 542000,
        status: 1,
    },
    {
        id: "6",
        date: "5/11/2023",
        invoiceNo: "1LC3XQ",
        payer: "Han Kaya Limited",
        payee: "Man Cheap Limited",
        amount: 6285000,
        status: 3,
    },
    {
        date: "5/14/2023",
        invoiceNo: "1LC3XQ",
        payer: "Green Kaya Limited",
        payee: "Des Cheap Limited",
        amount: 242000,
        status: 2,
    },
]